[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "mkdir -p data && python3 seed.py && python3 server.py"
